export enum ActionType {
    CHANGE_MODE = 'THEME_CHANGE_MODE',

    NETWORK_WALLET_CONNECT = 'NETWORK_WALLET_CONNECT',
    NETWORK_WALLET_CONNECT_SUCCESS = 'NETWORK_WALLET_CONNECT_SUCCESS',
    NETWORK_WALLET_CONNECT_FAIL = 'NETWORK_WALLET_CONNECT_FAIL',
    NETWORK_WALLET_DISCONNECT = 'NETWORK_WALLET_DISCONNECT',
    NETWORK_WALLET_DISCONNECT_SUCCESS = 'NETWORK_WALLET_DISCONNECT_SUCCESS',
    NETWORK_WALLET_DISCONNECT_FAIL = 'NETWORK_WALLET_DISCONNECT_FAIL',
    NETWORK_ACCOUNT_CHANGE = 'NETWORK_ACCOUNT_CHANGE',
    NETWORK_ACCOUNT_CHANGE_SUCCESS = 'NETWORK_ACCOUNT_CHANGE_SUCCESS',
    NETWORK_ACCOUNT_CHANGE_FAIL = 'NETWORK_ACCOUNT_CHANGE_FAIL',
    NETWORK_CHANGE = 'NETWORK_CHANGE',
    NETWORK_CHANGE_SUCCESS = 'NETWORK_CHANGE_SUCCESS',
    NETWORK_CHANGE_FAIL = 'NETWORK_CHANGE_FAIL',
    NETWORK_CONNECT = 'NETWORK_CONNECT',
    NETWORK_DISCONNECT = 'NETWORK_DISCONNECT'
}